### PR TITLE
Tc001 hakki

### PR DESCRIPTION
**Pull request by HakkiSabanci**

### CODE REVIEW

**Review by Zarina92c — APPROVED** [review]
Yes looks fine. Maybe add print method and make it abstract class! Thank you for your hard wok!

**Review by HakkiSabanci — COMMENTED** [review]
I did my own review :D

**Comment by Tajigozel** [comment]
test

**Comment by ImanSa19** [comment]
Hello, am  I here? lol

**Review by Tajigozel — COMMENTED** [review]
test

**Comment by Zarina92c** [comment]
Ok i see you busy bees )

**Comment by Zarina92c** [comment]
I am saving all the pictures in the end of the course will make video

**Pull request merged**
